[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMonoNL NFM ExtraBold"
italic.family = "JetBrainsMono Nerd Font"

size = 14.0

[shell]
program = "/opt/homebrew/bin/fish"


[window]
option_as_alt = "Both" # other values are None, OnlyRight, Both]
