import = ["~/.config/alacritty/rose-pine.toml"]

[font]
normal = { family = "JetBrainsMonoNL NF", style = "Regular" }
bold = { family = "JetBrainsMonoNL NF", style = "Bold" }
italic = { family = "JetBrainsMonoNL NF", style = "Italic" }
bold_italic = { family = "JetBrainsMono NF", style = "Bold Italic" }

size = 14.0

[shell]
program = "/bin/zsh"

[window]
option_as_alt = "OnlyLeft" # other values are None, OnlyRight, Both]
