#!/usr/bin/env bash

# Switch between Ripgrep launcher mode (CTRL-R) and fzf filtering mode (CTRL-F)
rm -f /tmp/rg-fzf-{r,f}
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
INITIAL_QUERY="${*:-}"
: | fzf --ansi --disabled --query "$INITIAL_QUERY" \
	--bind "start:reload($RG_PREFIX {q})+unbind(ctrl-r)" \
	--bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
	--color "hl:-1:underline,hl+:-1:underline:reverse" \
	--prompt '1. ripgrep> ' \
	--delimiter : \
	--preview 'bat --color=always {1} --highlight-line {2}' \
	--preview-window '60%,+{2}+3/3,~3' \
	--bind 'enter:become(nvim {1} +{2})'
